linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - revive
    - gofmt

linters-settings:
  errcheck:
    exclude: dev/errcheck-exclude.txt
