version: '3'

services:
  backend:
    build: ./
    restart: always
    environment:
      TRAQ_ORIGIN: http://localhost:3000
      TRAQ_MARIADB_HOST: mysql
      TRAQ_ES_URL: http://es:9200
      TRAQ_PPROF: "true"
    entrypoint: dockerize -timeout 60s -wait tcp://mysql:3306 -wait tcp://es:9200
    command: ./traQ serve --dev --skip-init-emojis
    expose:
      - "80"
      - "6060"
    ports:
      - "6060:6060"
    depends_on:
      - mysql
      - es
    volumes:
      - app:/app/storage

  frontend:
    image: caddy:latest
    restart: always
    expose:
      - "80"
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./dev/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./dev/frontend:/usr/share/caddy:ro

  mysql:
    image: mariadb:10.6.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: traq
    # conohaのDBのデフォルトCharsetはutf8
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    expose:
      - "3306"
    ports:
      - "3002:3306"
    volumes:
      - mysql:/var/lib/mysql

  es:
    image: ghcr.io/traptitech/es-with-sudachi:7.10.2-2.1.1-SNAPSHOT
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./dev/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./dev/es_jvm.options:/usr/share/elasticsearch/config/jvm.options.d/es_jvm.options
      - es:/usr/share/elasticsearch/data

  adminer:
    image: adminer:4.7.5
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: nette
    expose:
      - "8080"
    ports:
      - "3001:8080"

  botdebugger:
    image: golang:alpine
    restart: always
    volumes:
      - ./dev/bin:/app
    command: go run /app/bot_debugger.go -p 80

  s3:
    image: minio/minio:latest
    # 9000-API, 9001-Web
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: AKID
      MINIO_ROOT_PASSWORD: SECRETPASSWORD
      MINIO_DOMAIN: s3
    volumes:
      - s3:/data
    command: minio server /data --console-address :9001


volumes:
  app:
  mysql:
  es:
  s3:
