version: '3'

services:
  traq-backend:
    build: ./
    restart: always
    environment:
      TRAQ_ORIGIN: http://localhost:3000
      TRAQ_MARIADB_HOST: mysql
      TRAQ_PPROF: "true"
      TRAQ_GORMLOGMODE: "true"
      TRAQ_INITDATADIR: /initdata
    entrypoint: dockerize -timeout 60s -wait tcp://mysql:3306
    command: ./traQ
    expose:
      - "80"
      - "6060"
    ports:
      - "6060:6060"
    depends_on:
      - mysql
    networks:
      - traQnet
    volumes:
      - ./dev/data:/initdata:ro
      - ./dev/keys:/app/keys:ro

  traq-frontend:
    image: trap/traq-ui
    restart: always
    expose:
      - "80"
    networks:
      - traQnet

  reverse-proxy:
    image: abiosoft/caddy:0.11.5-no-stats
    restart: always
    expose:
      - "80"
    ports:
      - "3000:80"
    depends_on:
      - traq-backend
      - traq-frontend
    networks:
      - traQnet
    volumes:
      - ./dev/Caddyfile:/etc/Caddyfile:ro

  mysql:
    image: mariadb:10.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: traq
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    expose:
      - "3306"
    ports:
      - "3002:3306"
    networks:
      - traQnet
      - adminNet

  adminer:
    image: adminer:4.6.3
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: nette
    expose:
      - "8080"
    ports:
      - "3001:8080"
    networks:
      - adminNet

networks:
  traQnet:
  adminNet:
