version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:latest
      - image: circleci/mysql:latest-ram
        environment:
          - MYSQL_DATABASE=traq
          - MYSQL_ROOT_PASSWORD=password

    working_directory: /go/src/github.com/traPtitech/traQ

    steps:
      - checkout

      - run:
          name: Install tools/packages
          command: make init

      - run:
          name: gofmt
          when: always
          command: (! gofmt -s -d `find . -path "./vendor" -prune -o -type f -name "*.go" -print` | grep ^)
      - run:
          name: golint
          when: always
          command: golint -set_exit_status
      - run:
          name: go vet
          when: always
          command: go vet ./...

      - run:
          name: Setup DB
          when: always
          command: |
            dockerize -wait tcp://localhost:3306 -timeout 1m
            go run .circleci/init.go

      - run:
          name: go test
          when: always
          command: ./.circleci/go.test.sh
      - run:
          name: go build
          when: always
          command: go build -o traq

      - run:
          name: Upload coverage data
          command: bash <(curl -s https://codecov.io/bash)

      - store_artifacts:
          path: /go/src/github.com/traPtitech/traQ/traq
          destination: traq
