version: 2.1

executors:
  default:
    docker:
      - image: circleci/golang:1.13.0
        environment:
          - GO111MODULE: "on"
          - GOCACHE: "/tmp/go/cache"
    working_directory: ~/workspace

commands:
  restore_mod:
    steps:
      - restore_cache:
          keys:
            - gomod-{{ checksum "go.mod" }}

jobs:
  gomod:
    executor: default
    steps:
      - checkout
      - restore_mod
      - run:
          when: always
          command: go mod download
      - save_cache:
          key: gomod-{{ checksum "go.mod" }}
          when: always
          paths:
            - /go/pkg/mod/cache
  test:
    docker:
      - image: circleci/golang:1.13.0
      - image: circleci/mariadb:10.0.38-ram
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
        environment:
          - MYSQL_DATABASE: "traq"
          - MYSQL_ROOT_PASSWORD: "password"
    working_directory: ~/workspace
    steps:
      - run:
          name: install imagemagick
          command: sudo apt-get update && sudo apt-get install -y imagemagick
      - checkout
      - restore_mod
      - run:
          name: test
          command: |
            export TRAQ_IMAGEMAGICK=`which convert`
            dockerize -wait tcp://localhost:3306 -timeout 1m 2>/dev/null
            go test ./... -coverprofile=coverage.txt -race -vet=off


workflows:
  version: 2
  main:
    jobs:
      - gomod:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - test:
          requires:
            - gomod
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
